import type {Starter} from './starter';
import raw from '@/data/catalog.json';
export type Entry={id:string;name:string;kind:string;group:string;tags:string;requirements:string;usage:string;effect:string;page:number;label:string;summary:string;summaryLanguage:string};
export const catalog=raw as Entry[];
export const skills=[['Acrobatics','Acrobacias','Cuerpo'],['Athletics','Atletismo','Cuerpo'],['Combat','Combate','Cuerpo'],['Intimidate','Intimidación','Cuerpo'],['Stealth','Sigilo','Cuerpo'],['Survival','Supervivencia','Cuerpo'],['General Education','Cultura general','Mente'],['Medicine Education','Medicina','Mente'],['Occult Education','Ocultismo','Mente'],['Pokémon Education','Conocimiento Pokémon','Mente'],['Technology Education','Tecnología','Mente'],['Guile','Astucia','Mente'],['Perception','Percepción','Mente'],['Charm','Encanto','Espíritu'],['Command','Liderazgo','Espíritu'],['Focus','Concentración','Espíritu'],['Intuition','Intuición','Espíritu']];
export const ranks=['','Patético','Sin entrenar','Novato','Competente','Experto','Maestro'];
export const stats=['HP','Attack','Defense','Special Attack','Special Defense','Speed'];
export const statLabels=['HP','Ataque','Defensa','Ataque especial','Defensa especial','Velocidad'];
export const types=['Bug','Dark','Dragon','Electric','Fairy','Fighting','Fire','Flying','Ghost','Grass','Ground','Ice','Normal','Poison','Psychic','Rock','Steel','Water'];
export const typeLabels=['Bicho','Siniestro','Dragón','Eléctrico','Hada','Lucha','Fuego','Volador','Fantasma','Planta','Tierra','Hielo','Normal','Veneno','Psíquico','Roca','Acero','Agua'];
export type Pick={uid:string;id:string;branch:string;source:string;config:Record<string,string>;confirmed:string[]};
export type Trainer={starter?:Starter;name:string;concept:string;age:string;appearance:string;story:string;notes:string;level:number;bg:string;adept:string;novice:string;weak:string[];ups:Record<string,number>;initial:number[];growth:number[];offense:number[];milestones:Record<string,string>;picks:Pick[]};
export const fresh=():Trainer=>({name:'',concept:'',age:'',appearance:'',story:'',notes:'',level:1,bg:'',adept:'',novice:'',weak:['','',''],ups:{},initial:[0,0,0,0,0,0],growth:[0,0,0,0,0,0],offense:[0,0],milestones:{},picks:[]});
export const clean=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’‘]/g,"'");
export const byId=(id:string)=>catalog.find(x=>x.id===id)!;
export const skillLabel=(s:string)=>skills.find(x=>x[0]===s)?.[1]||s;
export function baseRank(t:Trainer,s:string){return t.adept===s?4:t.novice===s?3:t.weak.includes(s)?1:2}
export function skillRank(t:Trainer,s:string){return baseRank(t,s)+(t.ups[s]||0)}
export function cap(l:number){return l>=12?6:l>=6?5:l>=2?4:3}
export function has(t:Trainer,name:string){return t.picks.some(p=>clean(byId(p.id)?.name||'')===clean(name))}
export function count(t:Trainer,name:string){return t.picks.filter(p=>clean(byId(p.id)?.name||'')===clean(name)).length}
export function branchOptions(e:Entry,t:Trainer):string[]{if(e.name==='Stat Ace')return stats.slice(1);if(e.name==='Type Ace'||e.name==='Elemental Connection')return types;if(e.name==='Style Expert')return ['Beauty','Cool','Cute','Smart','Tough'];if(e.name==='Researcher')return ['General','Apothecary','Artificer','Botany','Chemistry','Climatology','Occultism','Paleontology','Pokémon Care'];if(e.group==='Type Ace'||e.group==='Stat Ace'||e.group==='Style Expert'||e.tags.includes('[Branch]'))return t.picks.filter(p=>byId(p.id)?.name===e.group).map(p=>p.branch).filter(Boolean);return []}
export function budgets(t:Trainer){let feat=4+Math.floor((t.level-1)/2),edge=4+Math.floor(t.level/2),general=0,offense=0;for(const m of [5,10,20,30,40]){if(m>t.level)continue;let c=t.milestones[m];if(c==='features')general+=m===5?1:2;if(c==='edges'&&m!==5)edge+=2;if(c==='stats'){offense+=(m===5?2:0)+Math.max(0,Math.floor((Math.min(t.level,m===5?10:m+10)-m)/2));if(has(t,'Dabbler'))edge++}else if(c&&has(t,'Dabbler'))offense+=2}return {feat,edge,general,offense}}
export function statValues(t:Trainer){const vals=stats.map((s,i)=>(i===0?10:5)+(t.initial[i]||0)+(t.growth[i]||0)+(i===1?t.offense[0]||0:i===3?t.offense[1]||0:0));for(const p of t.picks){const e=byId(p.id);if(!e)continue;for(const tag of e.tags.match(/\[\+[^\]]+\]/g)||[]){const key=tag.slice(2,-1),idx=stats.indexOf(key);if(idx>=0)vals[idx]++;else if(stats.includes(p.config.stat))vals[stats.indexOf(p.config.stat)]++}if(e.group==='Martial Artist'){const art=t.picks.find(p=>byId(p.id)?.name==='Martial Artist');const map:Record<string,string>={Guts:'HP','Inner Focus':'Speed','Iron Fist':'Defense',Limber:'Speed',Reckless:'Attack',Technician:'Speed'};const s=map[art?.config.ability||''];if(s)vals[stats.indexOf(s)]++}}return vals}
export function derived(t:Trainer){let s=statValues(t);const a=skillRank(t,'Athletics'),c=skillRank(t,'Acrobatics'),v=has(t,'Traveler')?skillRank(t,'Survival'):0,j=Math.max(c,v),power=4+(Math.max(a,v)>=3?1:0)+(skillRank(t,'Combat')>=4?1:0)+(has(t,'Power Boost')?2:0);let overland=3+Math.floor((Math.max(a,c)+Math.max(Math.min(a,c),v))/2);let swim=Math.floor(overland/2);if(has(t,'Swimmer'))swim+=2;return {hp:t.level*2+s[0]*3+10,ap:5+Math.floor(t.level/5),physical:Math.min(6,Math.floor(s[2]/5)),special:Math.min(6,Math.floor(s[4]/5)),speed:Math.min(6,Math.floor(s[5]/5)),initiative:s[5],overland,swim,power,throwing:4+a+(has(t,'Throwing Masteries')?2:0),longJump:Math.floor(j/2)+(has(t,'Acrobat')?1:0),highJump:(j>=4?1:0)+(j>=6?1:0)+(has(t,'Acrobat')?1:0)}}
export type Check={text:string;ok:boolean;context?:boolean;key?:string};
const rankNames:Record<string,number>={Pathetic:1,Untrained:2,Novice:3,Adept:4,Expert:5,Master:6};
function groupSkills(t:Trainer,name:string,p?:Pick):string[]{const mapping:Record<string,string[]>={Mentor:['Charm','Intimidate','Intuition','Pokémon Education'],Fashionista:['Charm','Command','Guile','Intimidate','Intuition'],Provocateur:['Charm','Guile','Intimidate'],Rogue:['Acrobatics','Athletics','Stealth']};if(name==='Mentor'||name==='Fashionista'){const q=t.picks.find(x=>byId(x.id)?.name===name);return [q?.config.skill1,q?.config.skill2].filter(Boolean) as string[]}return mapping[name]||[]}
export function translatedReq(s:string){let r=s;for(const [en,es] of [...skills].sort((a,b)=>b[0].length-a[0].length))r=r.replaceAll(en,es);for(const [en,n] of Object.entries(rankNames))r=r.replaceAll(en,ranks[n]);return r.replace(/Prerequisites:/g,'Requisitos:').replace(/\bLevel\b/g,'Nivel').replace(/\bRank\b/g,'rango').replace(/\bFeatures\b/g,'rasgos').replace(/\bor\b/g,'o').replace(/\band\b/g,'y').replace(/Chosen Type/g,'tipo elegido').replace(/Chosen Stat/g,'estadística elegida')}
function contextual(text:string,p?:Pick):Check {return {text:translatedReq(text),ok:!!p?.confirmed.includes(text),context:true,key:text}}
// Unrecognized or campaign-dependent requirements are explicit confirmations, never silently approved.
function atom(t:Trainer,text:string,p?:Pick):Check[]{let s=text.trim().replace(/\.$/,'');if(!s||s==='None')return [];if(/^Level \d+$/.test(s)){let n=Number(s.match(/\d+/)![0]);return [{text:'Nivel '+n,ok:t.level>=n}]}
let m=s.match(/^(Novice|Adept|Expert|Master|Untrained) (.+)$/);if(m){let skill=m[2].replace(/ at .*$/,'');if(skills.some(x=>x[0]===skill)){let n=rankNames[m[1]];return [{text:skillLabel(skill)+' '+ranks[n],ok:skillRank(t,skill)>=n}]}}
m=s.match(/^(\d+|Three|Two|One|one|two|three) (?:of )?(.+?) (?:Skills? )?at (Novice|Adept|Expert|Master)(?: Rank)?(?: or higher)?$/);if(m){let n=({Three:3,Two:2,One:1,one:1,two:2,three:3} as Record<string,number>)[m[1]]||Number(m[1]);let list=skills.filter(x=>m![2].includes(x[0])).map(x=>x[0]);if(list.length)return [{text:translatedReq(s),ok:list.filter(x=>skillRank(t,x)>=rankNames[m![3]]).length>=n}]}
m=s.match(/^(?:any |An? |a )?(\d+|Three|Two|One|one|two|three)?\s*(?:(Education|Mentor|Fashionista|Provocateur|Rogue) )?Skills? (?:at |Ranked at )(Novice|Adept|Expert|Master)(?: Rank)?(?: or higher)?$/);if(m){let n=Number(m[1])||({Three:3,Two:2,One:1,one:1,two:2,three:3} as Record<string,number>)[m[1]]||1;let list=m[2]==='Education'?skills.filter(x=>x[0].includes('Education')).map(x=>x[0]):m[2]?groupSkills(t,m[2],p):skills.map(x=>x[0]);return [{text:translatedReq(s),ok:list.filter(x=>skillRank(t,x)>=rankNames[m![3]]).length>=n}]}
m=s.match(/^(\d+) (.+) Features$/);if(m){return [{text:m[1]+' rasgos de '+m[2],ok:t.picks.filter(q=>byId(q.id)?.group===m![2]&&byId(q.id)?.kind!=='reference').length>=Number(m[1])}]}
m=s.match(/^(.+) Rank (\d+)$/);if(m&&catalog.some(e=>e.name===m![1]))return [{text:m[1]+' · rango '+m[2],ok:count(t,m[1])>=Number(m[2])}];
m=s.match(/^Elemental Connection \((.+)\)$/);if(m)return [{text:'Conexión elemental · '+m[1],ok:t.picks.some(q=>byId(q.id)?.name==='Elemental Connection'&&q.branch===m![1])}];
m=s.match(/^(.+) as (?:Chosen Type|Chosen Stat)$/);if(m)return [{text:translatedReq(s),ok:!!p?.branch&&p.branch===m[1]}];
m=s.match(/^(\d+) (.+) Stat$/);if(m&&stats.includes(m[2]))return [{text:translatedReq(s),ok:statValues(t)[stats.indexOf(m[2])]>=Number(m[1])}];
const exact=catalog.find(e=>clean(e.name)===clean(s));if(exact)return [{text:exact.label,ok:has(t,exact.name)}];
if(s.includes(' or ')){const options=s.split(' or ');const checks=options.map(o=>atom(t,o,p));if(checks.every(c=>c.every(x=>!x.context)))return [{text:checks.map(c=>c.map(x=>x.text).join(' + ')).join(' o '),ok:checks.some(c=>c.every(x=>x.ok))}]}
return [contextual(s,p)]}
export function requirements(t:Trainer,e:Entry,p?:Pick):Check[]{let source=e.requirements;const special=specialRequirements(t,e,p);if(special)return special;const occurrence=t.picks.filter(q=>q.id===e.id&&q.branch===(p?.branch||'')).length+(p&&t.picks.some(q=>q.uid===p.uid)?0:1);const tier=[...source.matchAll(/(?:Rank (\d+) )?Prerequisites:/g)];if(tier.length){const parts=source.split(/Rank (\d+) Prerequisites:/);if(parts.length>1){let chosen=parts[0];for(let i=1;i<parts.length;i+=2)if(Number(parts[i])<=occurrence)chosen=parts[i+1];source=chosen}else{const alternatives=source.split('Prerequisites:').map(s=>parse(t,s,e,p));const ok=alternatives.find(c=>c.every(x=>x.ok));return ok||[contextual('Cumplir una alternativa: '+source,p)]}}
let checks=parse(t,source,e,p);if(e.kind==='feature'&&!['reference','general'].includes(e.kind)&&e.group!=='General'){const classPicks=t.picks.filter(q=>byId(q.id)?.name===e.group);checks.unshift({text:'Clase: '+(catalog.find(x=>x.name===e.group)?.label||e.group),ok:classPicks.length>0});if(e.tags.includes('[Branch]')&&e.group!=='Researcher')checks.push({text:'Especialización de '+e.group,ok:classPicks.some(q=>q.branch===p?.branch)});if(e.group==='Researcher'){const fields:Record<number,string>={140:'General',141:'Apothecary',142:'Artificer',143:'Botany',144:'Chemistry',145:'Climatology',146:'Occultism',147:'Paleontology',148:'Pokémon Care'};const field=fields[e.page];checks.push({text:'Campo de investigación: '+field,ok:classPicks.some(q=>[q.branch,q.config.field2].includes(field))})}}
if(e.name==='Elemental Connection')checks.push({text:'No tener Mystic Senses',ok:!has(t,'Mystic Senses')});if(e.name==='Mystic Senses')checks.push({text:'No tener Elemental Connection',ok:!has(t,'Elemental Connection')});return checks}
function parse(t:Trainer,text:string,e:Entry,p?:Pick):Check[]{let s=text.replace(/\bTechnology\b(?! Education)/g,'Technology Education').replace(/Medicine or Technology Edu/g,'Medicine Education or Technology Education').replace(/Cost:.*|Ingredients:.*|x2 Uses.*|X Daily.*/g,'').trim();const tokens:Check[][]=[];const addToken=(v:Check[])=>{let key='@'+tokens.length+'@';tokens.push(v);return key};
// Count/list forms are evaluated together, before commas become conjunctions.
s=s.replace(/(\d+|Two|Three|two|three) (?:of )?((?:(?:Acrobatics|Athletics|Stealth|Survival|Guile|Perception|Charm|Intimidate|Intuition|Command|Pokémon Education)(?:,? (?:or |and )?|,\s*)?)+)(?:Skills? )?at (Novice|Adept|Expert|Master)(?: Rank)?/g,match=>addToken(atom(t,match,p)));
s=s.replace(/(Novice|Adept|Expert|Master|Untrained) ((?:[A-Za-zé]+(?: Education)?)(?:, (?:[A-Za-zé]+(?: Education)?))*?,? or (?:[A-Za-zé]+(?: Education)?))(?=,|;|$)/g,(match,rank,list)=>{const names=list.split(/,? or |, /);if(names.every((v:string)=>skills.some(x=>x[0]===v)))return addToken([{text:names.map(skillLabel).join(' o ')+' · '+ranks[rankNames[rank]],ok:names.some((v:string)=>skillRank(t,v)>=rankNames[rank])}]);return match});
s=s.replace(/(Novice|Adept|Expert|Master) ([A-Za-z]+) and ([A-Za-z]+)(?=,|;|$)/g,(match,rank,a,b)=>{if([a,b].every(v=>skills.some(x=>x[0]===v)))return addToken([a,b].map(v=>({text:skillLabel(v)+' '+ranks[rankNames[rank]],ok:skillRank(t,v)>=rankNames[rank]})));return match});
return s.split(/;|,(?![^()]*\))/).flatMap(piece=>{piece=piece.trim();const m=piece.match(/^@(\d+)@$/);return m?tokens[Number(m[1])]:atom(t,piece,p)})}
export type Grant={key:string;label:string;kind:string;options?:string[];skillOnly?:boolean;skills?:string[];maxRank?:number;educationOnly?:boolean;ignoreSkills?:boolean};
export function grants(t:Trainer):Grant[]{const out:Grant[]=[{key:'training',label:'Entrenamiento inicial gratuito',kind:'training',options:catalog.filter(e=>e.tags.includes('[Training]')).map(e=>e.id),ignoreSkills:true}];for(const lvl of [2,6,12])if(t.level>=lvl)out.push({key:'skill-'+lvl,label:'Ventaja de habilidad de nivel '+lvl,kind:'edge',skillOnly:true,maxRank:lvl===2?3:lvl===6?4:5});for(const p of t.picks){const e=byId(p.id);if(!e)continue;if(['Hobbyist','Breadth of Knowledge'].includes(e.name))for(let n=0;n<3;n++)out.push({key:p.uid+'-'+n,label:e.label+' · ventaja '+(n+1),kind:'edge',skillOnly:e.name==='Hobbyist',educationOnly:e.name==='Breadth of Knowledge'});if(e.name==='Capture Specialist'||e.name==='Advanced Capture Techniques')for(let n=0;n<2;n++)out.push({key:p.uid+'-tech-'+n,label:e.label+' · técnica '+(n+1),kind:'reference',options:catalog.filter(x=>x.group==='Capture Specialist'&&x.kind==='reference').map(x=>x.id)});if(e.name==='Commander')out.push({key:p.uid+'-order',label:'Orden de Comandante',kind:'general',options:['ravager-orders','marksman-orders','trickster-orders','guardian-orders','precision-orders'],ignoreSkills:true});if(e.name==='Elite Trainer')out.push({key:p.uid+'-training',label:'Entrenamiento de élite',kind:'training',options:catalog.filter(x=>x.tags.includes('[Training]')).map(x=>x.id),ignoreSkills:true});if(e.name==='Capture Skills')out.push({key:p.uid+'-skill',label:'Capture Skills · mejora de habilidad',kind:'edge',skillOnly:true,skills:['Acrobatics','Athletics','Stealth','Survival','Guile','Perception']});if(e.name==='Researcher')out.push({key:p.uid+'-research',label:'Rasgo de investigación inicial',kind:'research'});if(e.name==='Dilettante'){out.push({key:p.uid+'-edge',label:'Diletante · ventaja',kind:'edge',options:['acrobat','apricorn-balls','basic-balls','basic-cooking','basic-martial-arts','beast-master','breeder','dynamism','gem-lore','grace','green-thumb','groomer','instinctive-aptitude','instruction','intimidating-presence','iron-mind','medic-training','mounted-prowess','repel-crafter','slippery','swimmer','train-the-reserves'],ignoreSkills:true},{key:p.uid+'-feature',label:'Diletante · rasgo',kind:'general',options:['command-versatility','commander-s-voice','defender','dive','first-aid-expertise','let-me-help-you-with-that','pok-ball-crafter','pok-maniac','press','quick-switch','skill-monkey','species-savant','agility-training','brutal-training','focused-training','inspired-training','tutoring','walk-it-off'],ignoreSkills:true})}}
return out}
export function allocation(t:Trainer){const b=budgets(t),pool=grants(t).filter(g=>g.kind==='edge'&&(g.skillOnly||g.educationOnly)),jobs:{skill:string;to:number}[]=[];for(const [sk,n] of Object.entries(t.ups))for(let i=1;i<=n;i++)jobs.push({skill:sk,to:baseRank(t,sk)+i});jobs.sort((a,b)=>b.to-a.to);let free=0;const used=new Set<number>();pool.sort((a,b)=>(a.maxRank||6)-(b.maxRank||6));for(const g of pool){if(t.picks.some(p=>p.source===g.key))continue;const i=jobs.findIndex((j,i)=>!used.has(i)&&j.to<=(g.maxRank||cap(t.level))&&(!g.educationOnly||j.skill.includes('Education'))&&(!g.skills||g.skills.includes(j.skill)));if(i>=0){used.add(i);free++}}const regular=t.picks.filter(p=>byId(p.id)?.kind==='edge'&&p.source==='edge').length;return {edgeUsed:regular+jobs.length-free,edgeMax:b.edge,freeSkillUsed:free+pool.filter(g=>t.picks.some(p=>p.source===g.key)).length,freeSkillMax:pool.length,featUsed:t.picks.filter(p=>p.source==='feature').length,featMax:b.feat,generalUsed:t.picks.filter(p=>p.source==='general').length,generalMax:b.general}}
export function canSource(t:Trainer,e:Entry,source:string){const b=allocation(t);if(source==='edge')return e.kind==='edge'&&b.edgeUsed<b.edgeMax;if(source==='feature')return ['class','feature','general'].includes(e.kind)&&b.featUsed<b.featMax;if(source==='general')return (e.kind==='general'||e.group==='Hobbyist')&&b.generalUsed<b.generalMax;const g=grants(t).find(g=>g.key===source);if(!g||t.picks.some(p=>p.source===source))return false;if(g.skillOnly)return false;if(g.educationOnly){if(e.kind!=='edge'||!e.requirements.includes('Education'))return false;const next={...t,picks:[...t.picks,{uid:'allocation-check',id:e.id,source,branch:'',config:{},confirmed:[]}]};return allocation(next).edgeUsed<=b.edgeMax}if(g.options)return g.options.includes(e.id);if(g.kind==='research')return e.group==='Researcher'&&e.kind==='feature';return g.kind===e.kind}
export function maxCopies(e:Entry){if(e.name==='Capture Skills')return 2;const rank=e.tags.match(/Ranked (\d+)/);if(rank)return Number(rank[1]);if(e.tags.includes('[Branch]'))return 1;if(/may (?:be taken|take this (?:Edge|Feature)) multiple times/i.test(e.effect))return 99;return 1}
export function pickChecks(t:Trainer,e:Entry,p:Pick){const grant=grants(t).find(g=>g.key===p.source);let checks=requirements(t,e,p);if(grant?.ignoreSkills)checks=checks.map(c=>skills.some(s=>c.text.includes(s[1]))&&!c.context?{...c,ok:true,text:c.text+' (exento por concesión)'}:c);if(p.source==='training')checks=[];if(e.kind==='class')checks.push({text:'Máximo cuatro clases',ok:t.picks.filter(q=>byId(q.id)?.kind==='class').length<4});const copies=t.picks.filter(q=>q.id===e.id&&(!e.tags.includes('[Branch]')||q.branch===p.branch)).length;checks.push({text:'Límite de rangos / repeticiones',ok:copies<maxCopies(e)});if(branchOptions(e,t).length)checks.push({text:'Elegir especialización',ok:branchOptions(e,t).includes(p.branch)});if(e.tags.match(/\[\+(?:Any|.* or )/))checks.push({text:'Elegir mejora de estadística',ok:stats.includes(p.config.stat)});checks.push({text:'Elección disponible en el presupuesto',ok:canSource(t,e,p.source)});return checks}
export function issues(t:Trainer){let errors:string[]=[];const all=[t.adept,t.novice,...t.weak];if(all.some(x=>!skills.some(s=>s[0]===x))||new Set(all).size!==5)errors.push('Trasfondo: elige cinco habilidades distintas (una competente, una novata y tres patéticas).');if(t.initial.reduce((a,b)=>a+b,0)!==10)errors.push('Reparte los 10 puntos iniciales de estadísticas.');if(t.growth.reduce((a,b)=>a+b,0)!==t.level-1)errors.push('Reparte '+(t.level-1)+' puntos de estadísticas por nivel.');if(t.offense.reduce((a,b)=>a+b,0)!==budgets(t).offense)errors.push('Completa los puntos ofensivos de los hitos.');for(const m of [5,10,20,30,40])if(t.level>=m&&!t.milestones[m])errors.push('Elige la recompensa del hito de nivel '+m+'.');for(const [sk,n] of Object.entries(t.ups)){if(skillRank(t,sk)>Math.max(baseRank(t,sk),cap(t.level)))errors.push(skillLabel(sk)+': excede el rango permitido por nivel.');if(t.level===1&&t.weak.includes(sk)&&n>0)errors.push(skillLabel(sk)+': no puedes mejorar una habilidad patética de trasfondo durante la creación de nivel 1.')}
const a=allocation(t);if(a.edgeUsed>a.edgeMax)errors.push('Has gastado más ventajas de las disponibles.');if(a.featUsed>a.featMax||a.generalUsed>a.generalMax)errors.push('Has gastado más rasgos de los disponibles.');for(const p of t.picks){const e=byId(p.id);if(!e){errors.push('Una elección no existe en el catálogo.');continue}let temp={...t,picks:t.picks.filter(q=>q.uid!==p.uid)};const checks=pickChecks(temp,e,p);const bad=checks.filter(c=>!c.ok); if(bad.length)errors.push(e.label+': '+bad.map(c=>c.text).join('; '))}return errors}
const linked:Record<string,string[]>={Bug:['Command','Survival'],Dark:['Guile','Stealth'],Dragon:['Command','Intimidate'],Electric:['Focus','Technology Education'],Fairy:['Charm','Guile'],Fighting:['Combat','Intuition'],Fire:['Focus','Intimidate'],Flying:['Acrobatics','Perception'],Ghost:['Intimidate','Occult Education'],Grass:['Survival','General Education'],Ground:['Perception','Intuition'],Ice:['Athletics','Survival'],Normal:['Charm','Intuition'],Poison:['Intimidate','Stealth'],Psychic:['Focus','Occult Education'],Rock:['Combat','Survival'],Steel:['Athletics','Intimidate'],Water:['Athletics','Intuition']};
function specialRequirements(t:Trainer,e:Entry,p?:Pick):Check[]|null{const anySkill=(list:string[],rank:number,num=1):Check=>({text:(num>1?num+' de: ':'')+list.map(skillLabel).join(' / ')+' · '+ranks[rank],ok:list.filter(s=>skillRank(t,s)>=rank).length>=num});
if(e.name==='Capture Specialist')return [anySkill(['Acrobatics','Athletics','Stealth','Survival'],3),anySkill(['Guile','Perception'],3)];
if(e.name==='Advanced Capture Techniques'){const rank=count(t,e.name)+1;return [{text:'Capture Specialist',ok:has(t,'Capture Specialist')},...(rank===1?[]:[anySkill(['Acrobatics','Athletics','Stealth','Survival','Guile','Perception'],rank===2?4:5,rank===4?3:2)])]}
if(e.name==='Stat Ace')return [anySkill(['Command','Focus'],3),contextual(has(t,'Ace Trainer')||has(t,'Style Expert')?'Tienes un Pokémon con '+(p?.branch||'la estadística elegida')+' de 15 o más':'Tienes tres Pokémon con '+(p?.branch||'la estadística elegida')+' de 20 o más',p)];
if(e.name==='Style Expert')return [contextual(has(t,'Coordinator')?'Tienes un Pokémon con 3d6 de Pokochos en '+(p?.branch||'el estilo elegido'):'Tienes tres Pokémon con 3d6 de Pokochos en '+(p?.branch||'el estilo elegido'),p)];
if(e.name==='Type Ace'){const selected=p?.branch||'';const conn=t.picks.some(q=>byId(q.id)?.name==='Elemental Connection'&&q.branch===selected);return [anySkill(linked[selected]||[],3),contextual(conn?'Tienes un Pokémon del tipo '+selected:'Tienes dos Pokémon distintos del tipo '+selected,p)]}
if(e.group==='Type Ace'&&e.kind==='feature'){const selected=p?.branch||'';let req=e.requirements.replace(/Type-?Linked Skill|Type Linked Skill/g,'Type-Linked Skill');let checks:Check[]=[{text:'Especialización Type Ace · '+selected,ok:t.picks.some(q=>byId(q.id)?.name==='Type Ace'&&q.branch===selected)}];const rank=req.match(/Type-Linked Skill at (Novice|Adept|Expert|Master)/);if(rank)checks.push(anySkill(linked[selected]||[],rankNames[rank[1]]));let other=req.replace(/,? Type-Linked Skill at (Novice|Adept|Expert|Master)\.?/,'');other=other.replace('Close Quaters Mastery','Close Quarters Mastery');for(const clause of other.split(',').map(s=>s.trim())){if(clause==='Type Ace')continue;if(clause.match(/ as Chosen Type$/)){checks.push({text:translatedReq(clause),ok:selected===clause.replace(' as Chosen Type','')});continue}let m=clause.match(/^(\d+) Type Ace Features$/);if(m){checks.push({text:m[1]+' rasgos de Type Ace · '+selected,ok:t.picks.filter(q=>byId(q.id)?.group==='Type Ace'&&q.branch===selected).length>=Number(m[1])});continue}const found=catalog.find(x=>clean(x.name).replace(/!/g,'')===clean(clause).replace(/!/g,''));if(found)checks.push({text:found.label+' · '+selected,ok:t.picks.some(q=>q.id===found.id&&q.branch===selected)});else checks.push(...atom(t,clause,p))}return checks}
return null}

export function skillBonus(t:Trainer,sk:string){let n=0;for(const p of t.picks){const e=byId(p.id);if(e?.name==='Skill Enhancement'&&[p.config.skill1,p.config.skill2].includes(sk))n+=2;if(e?.name==='Categoric Inclination'&&skills.find(x=>x[0]===sk)?.[2]===p.config.category)n++;if(e?.name==='Scholar'&&(sk.includes('Education')||sk==='Survival'))n++}return n}
